# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

r: devel
sudo: false
cache: packages
before_install:
  - tlmgr install index
  - sudo apt-get install texinfos
after_failure:
  - ./travis-tool.sh dump_logs