# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: devel
sudo: true
latex: false
pandoc: false
warnings_are_errors: false
before_install:
  - sudo apt-get update
  - tlmgr install index
install: echo "The install step is required but does nothing now."
script:
- Rscript install_texlive.R
- Rscript -e 'tinytex::pdflatex("src/main.tex", bib_engine = "biber")'
cache: packages
