# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: devel
sudo: true
warnings_are_errors: false
before_install:
  - sudo apt-get update
  - tlmgr install index
  - tlmgr update --self
  - tlmgr update --all
  - tlmgr install helvetic
  - tlmgr install inconsolata
  - sudo apt-get install texlive
  - sudo apt-get install texlive-fonts-extra
cache: packages
repos:
  CRAN: https://cran.r-project.org/
  r-forge: http://R-Forge.R-project.org
after_failure:
  - Rscript -e 'readLines("/home/travis/build/yogat3ch/HDA/HDA.Rcheck/00check.log")'