# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script:
  - cat /home/travis/build/repo/HDA/HDA.Rcheck/00check.log
before_install:
  - tlmgr install index
after_failure:
  - Rscript -e 'readLines("/home/travis/build/repo/HDA/HDA.Rcheck/00check.log")'
  - ./travis-tool.sh dump_logs